# Generated by Django 2.1.7 on 2019-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='玩家昵称', max_length=20)),
                ('game_name', models.CharField(help_text='游戏名', max_length=40)),
                ('duration', models.IntegerField(default=0, help_text='游戏时长')),
                ('platform', models.CharField(help_text='游戏平台', max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'ordering': ['duration', 'create_time'],
            },
        ),
    ]
