# Generated by Django 2.1.7 on 2019-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='duration',
            field=models.CharField(help_text='游戏时长', max_length=40),
        ),
        migrations.AlterField(
            model_name='rank',
            name='game_name',
            field=models.CharField(help_text='游戏名称', max_length=40),
        ),
        migrations.AlterField(
            model_name='rank',
            name='platform',
            field=models.IntegerField(choices=[(1, '游聚游戏平台'), (2, 'Nestopia模拟器'), (3, '小霸王游戏机')], default=1, help_text='游戏平台'),
        ),
    ]
