# Generated by Django 2.1.7 on 2019-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20190613_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='platform',
            field=models.IntegerField(choices=[(0, '其他'), (1, '游聚游戏平台'), (2, 'Nestopia模拟器'), (3, '小霸王游戏机')], default=1, help_text='游戏平台'),
        ),
    ]
